// Generates every ByteShare icon asset from one set of shapes (the split-card mark,
// traced from the logo artwork in the repo root).
// Usage (needs `npm i sharp`): node make_icons.js play-store --install .
const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

const INK = "#18181F";
const GREEN = "#4DDB25"; // sampled from the logo artwork
const CREAM = "#FDFBF0";

// Mark traced on the 1254px source image; its bounding box is x 101..1153, y 238..1016.
const MARK = {
  x: 101, y: 238, w: 1052, h: 778,
  paths: [
    // left card, wrapping around the centre ring
    "M177,238H614V443H507A90,90 0 0 0 417,533V763A32,32 0 0 0 449,795H564V942H177A76,76 0 0 1 101,866V314A76,76 0 0 1 177,238Z",
    // right card
    "M653,309H1077A76,76 0 0 1 1153,385V940A76,76 0 0 1 1077,1016H605V795H742A90,90 0 0 0 832,705V473A30,30 0 0 0 802,443H653Z",
    // inner left half
    "M468,534A40,40 0 0 1 508,494H614V595H564V744H468Z",
    // inner right half
    "M653,494H782V704A40,40 0 0 1 742,744H605V643H653Z",
  ],
};

// Placement in the 108dp adaptive canvas (safe zone = 66dp circle): 52dp wide, centred.
const SCALE = 52 / MARK.w;
const OFFSET_X = 54 - (MARK.x + MARK.w / 2) * SCALE;
const OFFSET_Y = 54 - (MARK.y + MARK.h / 2) * SCALE;
const r = (n) => +n.toFixed(4);

const markSvg = (fill = GREEN) =>
  `<g transform="translate(${r(OFFSET_X)} ${r(OFFSET_Y)}) scale(${r(SCALE)})">
     ${MARK.paths.map((d) => `<path d="${d}" fill="${fill}"/>`).join("\n     ")}
   </g>`;

// viewBox 18..90 = the visible 72dp of an adaptive icon, used for legacy + store icons
const iconSvg = ({ shape = "square", size = 512 } = {}) => {
  const clip = shape === "circle"
    ? `<clipPath id="c"><circle cx="54" cy="54" r="36"/></clipPath>`
    : shape === "rounded"
      ? `<clipPath id="c"><rect x="18" y="18" width="72" height="72" rx="13"/></clipPath>`
      : `<clipPath id="c"><rect x="18" y="18" width="72" height="72"/></clipPath>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="18 18 72 72">
  <defs>${clip}</defs>
  <g clip-path="url(#c)"><rect x="0" y="0" width="108" height="108" fill="${CREAM}"/>${markSvg()}</g>
</svg>`;
};

const featureSvg = () => `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="500" viewBox="0 0 1024 500">
  <rect width="1024" height="500" fill="${CREAM}"/>
  <!-- icon tile with offset shadow -->
  <rect x="122" y="112" width="276" height="276" rx="48" fill="${INK}"/>
  <rect x="110" y="100" width="276" height="276" rx="48" fill="#FFFFFF" stroke="${INK}" stroke-width="8"/>
  <svg x="110" y="100" width="276" height="276" viewBox="18 18 72 72">${markSvg()}</svg>
  <text x="450" y="235" font-family="Arial Black, Segoe UI Black, Arial, sans-serif" font-weight="900"
        font-size="92" fill="${INK}">ByteShare</text>
  <text x="454" y="292" font-family="Segoe UI, Arial, sans-serif" font-weight="600"
        font-size="34" fill="${INK}">Your screen time pays the bill.</text>
  <rect x="460" y="330" width="400" height="56" rx="28" fill="${INK}"/>
  <rect x="454" y="324" width="400" height="56" rx="28" fill="${GREEN}" stroke="${INK}" stroke-width="4"/>
  <text x="654" y="360" text-anchor="middle" font-family="Arial Black, Segoe UI Black, Arial, sans-serif"
        font-weight="900" font-size="20" fill="${INK}">SPLIT BILLS BY SCREEN TIME</text>
</svg>`;

// ---------- Android vector drawables (same shapes) ----------
const vector = (body, { width = 108, height = 108, vw = 108, vh = 108 } = {}) => `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${width}dp"
    android:height="${height}dp"
    android:viewportWidth="${vw}"
    android:viewportHeight="${vh}">
${body}
</vector>
`;
const group = ({ scale = 1, tx, ty }, inner) => `    <group
${scale === 1 ? "" : `        android:scaleX="${r(scale)}"
        android:scaleY="${r(scale)}"
`}        android:translateX="${r(tx)}"
        android:translateY="${r(ty)}">
${inner}
    </group>`;
const vpaths = (fill) => MARK.paths.map((d) => `        <path
            android:fillColor="${fill}"
            android:pathData="${d}" />`).join("\n");
const adaptiveGroup = (fill) => group({ scale: SCALE, tx: OFFSET_X, ty: OFFSET_Y }, vpaths(fill));

const foregroundXml = vector(`    <!-- ByteShare split-card mark (generated by play-store/make_icons.js) -->
${adaptiveGroup(GREEN)}`);

const monochromeXml = vector(`    <!-- Single-colour mark for Android 13+ themed icons (generated by play-store/make_icons.js) -->
${adaptiveGroup("#FF000000")}`);

const backgroundXml = vector(`    <path
        android:fillColor="${CREAM}"
        android:pathData="M0,0h108v108h-108z" />`);

// Tightly cropped mark for in-app use (login header etc.)
const logoXml = vector(`    <!-- ByteShare split-card mark (generated by play-store/make_icons.js) -->
${group({ tx: -MARK.x, ty: -MARK.y }, vpaths(GREEN))}`,
  { width: 80, height: r(80 * MARK.h / MARK.w), vw: MARK.w, vh: MARK.h });

const adaptiveXml = `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
`;

const png = (svg, file) => sharp(Buffer.from(svg)).png().toFile(file);

(async () => {
  const outDir = process.argv[2];
  fs.mkdirSync(outDir, { recursive: true });
  await png(iconSvg({ shape: "square", size: 512 }), path.join(outDir, "icon-512.png"));
  // Play requires the feature graphic as JPEG or 24-bit PNG (no alpha)
  await sharp(Buffer.from(featureSvg())).flatten({ background: CREAM }).removeAlpha()
    .png().toFile(path.join(outDir, "feature-graphic-1024x500.png"));
  fs.writeFileSync(path.join(outDir, "icon.svg"), iconSvg({ shape: "square", size: 512 }));
  // Preview of how launchers mask it
  await png(iconSvg({ shape: "circle", size: 192 }), path.join(outDir, "preview-circle.png"));
  await png(iconSvg({ shape: "rounded", size: 192 }), path.join(outDir, "preview-rounded.png"));

  const i = process.argv.indexOf("--install");
  if (i === -1) return;
  const res = path.join(process.argv[i + 1], "app", "src", "main", "res");
  fs.writeFileSync(path.join(res, "drawable", "ic_launcher_foreground.xml"), foregroundXml);
  fs.writeFileSync(path.join(res, "drawable", "ic_launcher_background.xml"), backgroundXml);
  fs.writeFileSync(path.join(res, "drawable", "ic_launcher_monochrome.xml"), monochromeXml);
  fs.writeFileSync(path.join(res, "drawable", "ic_logo_byteshare.xml"), logoXml);
  fs.writeFileSync(path.join(res, "mipmap-anydpi-v26", "ic_launcher.xml"), adaptiveXml);
  fs.writeFileSync(path.join(res, "mipmap-anydpi-v26", "ic_launcher_round.xml"), adaptiveXml);
  const densities = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };
  for (const [density, size] of Object.entries(densities)) {
    const dir = path.join(res, `mipmap-${density}`);
    for (const name of ["ic_launcher.webp", "ic_launcher_round.webp"]) {
      fs.rmSync(path.join(dir, name), { force: true });
    }
    await png(iconSvg({ shape: "rounded", size }), path.join(dir, "ic_launcher.png"));
    await png(iconSvg({ shape: "circle", size }), path.join(dir, "ic_launcher_round.png"));
  }
  console.log("installed into", res);
})().catch((e) => { console.error(e); process.exit(1); });
