package com.example.byteshare.data

import android.content.Context
import android.util.Log
import androidx.credentials.CredentialManager
import androidx.credentials.CredentialManagerCallback
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.GetCredentialResponse
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import java.util.concurrent.Executors

/**
 * Google Sign-In via Credential Manager + Firebase Auth.
 */
object AuthRepository {

    private const val TAG = "AuthRepository"

    private val auth: FirebaseAuth by lazy { FirebaseAuth.getInstance() }
    private val executor = Executors.newSingleThreadExecutor()

    val currentUser: FirebaseUser? get() = auth.currentUser
    val currentUserId: String? get() = auth.currentUser?.uid

    fun isSignedIn(): Boolean = auth.currentUser != null

    /**
     * Launches the Google account picker and signs the user into Firebase.
     * Callback is invoked on the main thread.
     */
    fun signInWithGoogle(
        context: Context,
        onResult: (FirebaseUser?, String?) -> Unit
    ) {
        // Generated by google-services plugin once an OAuth web client exists in google-services.json
        val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        if (resId == 0) {
            onResult(null, "Google Sign-In not configured: add SHA-1 in Firebase console and update google-services.json")
            return
        }
        val webClientId = context.getString(resId)

        val googleIdOption = GetGoogleIdOption.Builder()
            .setServerClientId(webClientId)
            .setFilterByAuthorizedAccounts(false)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        CredentialManager.create(context).getCredentialAsync(
            context,
            request,
            null,
            executor,
            object : CredentialManagerCallback<GetCredentialResponse, GetCredentialException> {
                override fun onResult(result: GetCredentialResponse) {
                    handleCredential(result, context, onResult)
                }

                override fun onError(e: GetCredentialException) {
                    Log.e(TAG, "Credential Manager failed", e)
                    postToMain(context) { onResult(null, e.message ?: "Sign-in cancelled") }
                }
            }
        )
    }

    private fun handleCredential(
        response: GetCredentialResponse,
        context: Context,
        onResult: (FirebaseUser?, String?) -> Unit
    ) {
        val credential = response.credential
        if (credential is CustomCredential &&
            credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
        ) {
            try {
                val googleCred = GoogleIdTokenCredential.createFrom(credential.data)
                val firebaseCred = GoogleAuthProvider.getCredential(googleCred.idToken, null)
                auth.signInWithCredential(firebaseCred)
                    .addOnSuccessListener { result ->
                        onResult(result.user, null)
                    }
                    .addOnFailureListener { e ->
                        Log.e(TAG, "Firebase sign-in failed", e)
                        onResult(null, e.message)
                    }
            } catch (e: Exception) {
                Log.e(TAG, "Invalid Google ID token", e)
                postToMain(context) { onResult(null, e.message) }
            }
        } else {
            postToMain(context) { onResult(null, "Unexpected credential type") }
        }
    }

    private fun postToMain(context: Context, block: () -> Unit) {
        android.os.Handler(context.mainLooper).post(block)
    }

    fun signOut(context: Context, onComplete: () -> Unit = {}) {
        auth.signOut()
        // Clear credential state so next sign-in shows the account picker
        CredentialManager.create(context).clearCredentialStateAsync(
            androidx.credentials.ClearCredentialStateRequest(),
            null,
            executor,
            object : CredentialManagerCallback<Void?, androidx.credentials.exceptions.ClearCredentialException> {
                override fun onResult(result: Void?) {
                    postToMain(context) { onComplete() }
                }

                override fun onError(e: androidx.credentials.exceptions.ClearCredentialException) {
                    Log.w(TAG, "clearCredentialState failed", e)
                    postToMain(context) { onComplete() }
                }
            }
        )
    }
}
